/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp5punto1;

import java.awt.Color;

/**
 *
 * @author Fran
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }
    
    private TareaSemaforo tarea1;
    private TareaAutos tarea2;
    private Thread th1;
    private Thread th2;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelLogin = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtLogin = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        resultadoButton = new javax.swing.JButton();
        sumaRadio = new javax.swing.JRadioButton();
        restaRadio = new javax.swing.JRadioButton();
        multiplicacionRadio = new javax.swing.JRadioButton();
        divisionRadio = new javax.swing.JRadioButton();
        txtNum1 = new javax.swing.JTextField();
        txtNum2 = new javax.swing.JTextField();
        txtRes = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        consigna2 = new javax.swing.JPanel();
        txtConsigna = new javax.swing.JLabel();
        radio1 = new javax.swing.JRadioButton();
        radio2 = new javax.swing.JRadioButton();
        buttonRespuesta = new javax.swing.JButton();
        consigna3 = new javax.swing.JPanel();
        txtConsigna1 = new javax.swing.JLabel();
        radio3 = new javax.swing.JRadioButton();
        radio4 = new javax.swing.JRadioButton();
        consigna1 = new javax.swing.JPanel();
        txtConsigna2 = new javax.swing.JLabel();
        radio5 = new javax.swing.JRadioButton();
        radio6 = new javax.swing.JRadioButton();
        consigna4 = new javax.swing.JPanel();
        txtConsigna3 = new javax.swing.JLabel();
        radio7 = new javax.swing.JRadioButton();
        radio8 = new javax.swing.JRadioButton();
        puntuacionLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        autoIzqLabel = new javax.swing.JLabel();
        autoDerLabel = new javax.swing.JLabel();
        iniciarButton = new javax.swing.JButton();
        semaforoPanel = new javax.swing.JPanel();
        rojoLabel = new javax.swing.JLabel();
        amarilloLabel = new javax.swing.JLabel();
        verdeLabel = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fran\\Documents\\NetBeansProjects\\tp5punto1\\autoder.png")); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(200, 100));
        jLabel3.setMinimumSize(new java.awt.Dimension(200, 100));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setForeground(new java.awt.Color(0, 153, 153));

        jLabel1.setText("Usuario");

        jLabel2.setText("Contraseña");

        jButton1.setText("Ingresar");
        jButton1.setAlignmentX(5.0F);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtUser)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtPass)
            .addComponent(txtLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jButton1)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtLogin))
        );

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Login", panelLogin);

        resultadoButton.setText("Resultado");
        resultadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoButtonActionPerformed(evt);
            }
        });

        buttonGroup5.add(sumaRadio);
        sumaRadio.setText("+");

        buttonGroup5.add(restaRadio);
        restaRadio.setText("-");

        buttonGroup5.add(multiplicacionRadio);
        multiplicacionRadio.setText("*");

        buttonGroup5.add(divisionRadio);
        divisionRadio.setText("/");

        txtRes.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNum1)
                    .addComponent(txtNum2)
                    .addComponent(resultadoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(txtRes))
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sumaRadio)
                    .addComponent(restaRadio)
                    .addComponent(multiplicacionRadio)
                    .addComponent(divisionRadio))
                .addGap(162, 162, 162))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(sumaRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(restaRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(multiplicacionRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(divisionRadio)
                            .addComponent(resultadoButton)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Calculadora", jPanel3);

        consigna2.setForeground(new java.awt.Color(0, 0, 0));

        txtConsigna.setText("¿Cuanto es 20+20?");

        buttonGroup2.add(radio1);
        radio1.setForeground(new java.awt.Color(0, 0, 0));
        radio1.setText("50");

        buttonGroup2.add(radio2);
        radio2.setForeground(new java.awt.Color(0, 0, 0));
        radio2.setText("40");

        javax.swing.GroupLayout consigna2Layout = new javax.swing.GroupLayout(consigna2);
        consigna2.setLayout(consigna2Layout);
        consigna2Layout.setHorizontalGroup(
            consigna2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consigna2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(consigna2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtConsigna)
                    .addComponent(radio1)
                    .addComponent(radio2))
                .addContainerGap())
        );
        consigna2Layout.setVerticalGroup(
            consigna2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consigna2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtConsigna)
                .addGap(29, 29, 29)
                .addComponent(radio1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radio2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonRespuesta.setText("Finalizar");
        buttonRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRespuestaActionPerformed(evt);
            }
        });

        txtConsigna1.setText("¿Cuanto es 8 + 8?");

        buttonGroup3.add(radio3);
        radio3.setForeground(new java.awt.Color(0, 0, 0));
        radio3.setText("18");

        buttonGroup3.add(radio4);
        radio4.setForeground(new java.awt.Color(0, 0, 0));
        radio4.setText("16");

        javax.swing.GroupLayout consigna3Layout = new javax.swing.GroupLayout(consigna3);
        consigna3.setLayout(consigna3Layout);
        consigna3Layout.setHorizontalGroup(
            consigna3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consigna3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(consigna3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtConsigna1)
                    .addComponent(radio3)
                    .addComponent(radio4))
                .addContainerGap())
        );
        consigna3Layout.setVerticalGroup(
            consigna3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consigna3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtConsigna1)
                .addGap(29, 29, 29)
                .addComponent(radio3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radio4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtConsigna2.setText("¿Cuanto es 5 + 5?");

        buttonGroup1.add(radio5);
        radio5.setForeground(new java.awt.Color(0, 0, 0));
        radio5.setText("10");

        buttonGroup1.add(radio6);
        radio6.setForeground(new java.awt.Color(0, 0, 0));
        radio6.setText("11");

        javax.swing.GroupLayout consigna1Layout = new javax.swing.GroupLayout(consigna1);
        consigna1.setLayout(consigna1Layout);
        consigna1Layout.setHorizontalGroup(
            consigna1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consigna1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(consigna1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtConsigna2)
                    .addComponent(radio5)
                    .addComponent(radio6))
                .addContainerGap())
        );
        consigna1Layout.setVerticalGroup(
            consigna1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consigna1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtConsigna2)
                .addGap(29, 29, 29)
                .addComponent(radio5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radio6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtConsigna3.setText("¿Cuanto es 50 + 30?");

        buttonGroup4.add(radio7);
        radio7.setForeground(new java.awt.Color(0, 0, 0));
        radio7.setText("80");

        buttonGroup4.add(radio8);
        radio8.setForeground(new java.awt.Color(0, 0, 0));
        radio8.setText("70");

        javax.swing.GroupLayout consigna4Layout = new javax.swing.GroupLayout(consigna4);
        consigna4.setLayout(consigna4Layout);
        consigna4Layout.setHorizontalGroup(
            consigna4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consigna4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(consigna4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtConsigna3)
                    .addComponent(radio7)
                    .addComponent(radio8))
                .addContainerGap())
        );
        consigna4Layout.setVerticalGroup(
            consigna4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consigna4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtConsigna3)
                .addGap(29, 29, 29)
                .addComponent(radio7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radio8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(consigna3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consigna1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(consigna2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consigna4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(40, 40, 40))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(puntuacionLabel))
                    .addComponent(buttonRespuesta))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(consigna2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consigna4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(buttonRespuesta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(puntuacionLabel)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(consigna1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consigna3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))))
        );

        jTabbedPane1.addTab("Examen", jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        autoIzqLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fran\\Documents\\NetBeansProjects\\tp5punto1\\autoizq.png")); // NOI18N

        autoDerLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fran\\Documents\\NetBeansProjects\\tp5punto1\\autoder.png")); // NOI18N

        iniciarButton.setText("Iniciar");
        iniciarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarButtonActionPerformed(evt);
            }
        });

        semaforoPanel.setBackground(new java.awt.Color(255, 255, 255));

        rojoLabel.setBackground(new java.awt.Color(204, 0, 0));
        rojoLabel.setForeground(new java.awt.Color(255, 0, 0));
        rojoLabel.setText("O");

        amarilloLabel.setForeground(new java.awt.Color(255, 255, 255));
        amarilloLabel.setText("O");

        verdeLabel.setForeground(new java.awt.Color(255, 255, 255));
        verdeLabel.setText("O");

        javax.swing.GroupLayout semaforoPanelLayout = new javax.swing.GroupLayout(semaforoPanel);
        semaforoPanel.setLayout(semaforoPanelLayout);
        semaforoPanelLayout.setHorizontalGroup(
            semaforoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(semaforoPanelLayout.createSequentialGroup()
                .addComponent(rojoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(amarilloLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(verdeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        semaforoPanelLayout.setVerticalGroup(
            semaforoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, semaforoPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(semaforoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rojoLabel)
                    .addComponent(amarilloLabel)
                    .addComponent(verdeLabel)))
        );

        resetButton.setText("Reiniciar");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(autoDerLabel))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(autoIzqLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(semaforoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(iniciarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetButton)
                .addGap(174, 174, 174))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(autoIzqLabel)
                .addGap(25, 25, 25)
                .addComponent(semaforoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(autoDerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iniciarButton)
                    .addComponent(resetButton))
                .addGap(19, 19, 19))
        );

        jTabbedPane1.addTab("Auto", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Almacena el usuario y contraseña ingresado por el usuario y verifica si se inicio sesion correctamente.
     * De no ser asi, muestra un mensaje de error.
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String user = txtUser.getText();
        String pass = txtPass.getText();
        if(user.equals("admin") && pass.equals("123456")){
            txtLogin.setText("Usted ha ingresado con el usuario: "+user);
            panelLogin.setBackground(Color.green);
            txtLogin.setForeground(Color.green);
        }else{
            txtLogin.setText("Usuario y/o contraseña incorrectos");
            panelLogin.setBackground(Color.red);
            txtLogin.setForeground(Color.red);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * Se fija cuales de las respuestas del examen fueron correctas y muestra en un label la puntuacion final.
     * @param evt 
     */
    private void buttonRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRespuestaActionPerformed
        int puntuacion = 0;
        if(radio5.isSelected()){
            puntuacion++;
            radio6.setForeground(Color.black);
        }
        else radio6.setForeground(Color.red);
        if(radio4.isSelected()){
            puntuacion++;
            radio3.setForeground(Color.black);
        }
        else radio3.setForeground(Color.red);
        if(radio2.isSelected()){
            puntuacion++;
            radio1.setForeground(Color.black);
        }
        else radio1.setForeground(Color.red);
        if(radio7.isSelected()){
            puntuacion++;
            radio8.setForeground(Color.black);
        }
        else radio8.setForeground(Color.red);
        puntuacionLabel.setText("Puntuacion: "+puntuacion+"/4");
    }//GEN-LAST:event_buttonRespuestaActionPerformed
    
    /**
     * Almacena los 2 numeros ingresados por el usuario y con un trycatch verifica si los datos son validos.
     * Luego dependiendo de que radioButton este seleccionado se suma, resta, multiplica o divide.
     * Muestra el resultado de la operacion en un jLabel.
     * @param evt 
     */
    private void resultadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoButtonActionPerformed
        try{
            txtRes.setForeground(Color.BLACK);
            float num1 = Float.parseFloat(txtNum1.getText());
            float num2 = Float.parseFloat(txtNum2.getText());
            if(sumaRadio.isSelected()){
                txtRes.setText(String.valueOf(num1 + num2));
            }else if(restaRadio.isSelected()){
                txtRes.setText(String.valueOf(num1 - num2));
            }else if(multiplicacionRadio.isSelected()){
                txtRes.setText(String.valueOf(num1 * num2));
            }else if(divisionRadio.isSelected()){
                txtRes.setText(String.valueOf(num1 / num2));
            }else{
                txtRes.setText("");
            }
        } catch (NumberFormatException e){ 
            txtRes.setText("Error");
            txtRes.setForeground(Color.RED);
        }
    }//GEN-LAST:event_resultadoButtonActionPerformed
    
    /**
     * Asigna una tarea a un hilo para hacer funcionar el semaforo y que cambie de color.
     * Asigna otra tarea a otro hilo, la cual se basa en hacer que los autos se muevan luego del tiempo que tarda el semaforo.
     * Deshabilita el boton de iniciar, para que no se superpongan las tareas.
     * @param evt 
     */
    private void iniciarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarButtonActionPerformed
        tarea1 = new TareaSemaforo(rojoLabel, amarilloLabel, verdeLabel, 700);
        tarea2 = new TareaAutos(autoDerLabel, autoIzqLabel, 100, 1500);
        th1 = new Thread(tarea1);
        th2 = new Thread(tarea2);
        th1.start();
        th2.start();
        iniciarButton.setEnabled(false);
    }//GEN-LAST:event_iniciarButtonActionPerformed
    
    /**
     * Reinicia la posicion de los autos y los colores del semaforo.
     * Desactiva las tareas en funcionamiento.
     * Vuelve a habilitar el boton para iniciar la simulacion
     * @param evt 
     */
    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        tarea1.desactivar();
        tarea2.desactivar();
        autoDerLabel.setLocation(373,153);
        autoIzqLabel.setLocation(0,42);
        rojoLabel.setForeground(Color.red);
        amarilloLabel.setForeground(Color.white);
        verdeLabel.setForeground(Color.white);
        iniciarButton.setEnabled(true);
    }//GEN-LAST:event_resetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amarilloLabel;
    private javax.swing.JLabel autoDerLabel;
    private javax.swing.JLabel autoIzqLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton buttonRespuesta;
    private javax.swing.JPanel consigna1;
    private javax.swing.JPanel consigna2;
    private javax.swing.JPanel consigna3;
    private javax.swing.JPanel consigna4;
    private javax.swing.JRadioButton divisionRadio;
    private javax.swing.JButton iniciarButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton multiplicacionRadio;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JLabel puntuacionLabel;
    private javax.swing.JRadioButton radio1;
    private javax.swing.JRadioButton radio2;
    private javax.swing.JRadioButton radio3;
    private javax.swing.JRadioButton radio4;
    private javax.swing.JRadioButton radio5;
    private javax.swing.JRadioButton radio6;
    private javax.swing.JRadioButton radio7;
    private javax.swing.JRadioButton radio8;
    private javax.swing.JButton resetButton;
    private javax.swing.JRadioButton restaRadio;
    private javax.swing.JButton resultadoButton;
    private javax.swing.JLabel rojoLabel;
    private javax.swing.JPanel semaforoPanel;
    private javax.swing.JRadioButton sumaRadio;
    private javax.swing.JLabel txtConsigna;
    private javax.swing.JLabel txtConsigna1;
    private javax.swing.JLabel txtConsigna2;
    private javax.swing.JLabel txtConsigna3;
    private javax.swing.JLabel txtLogin;
    private javax.swing.JTextField txtNum1;
    private javax.swing.JTextField txtNum2;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtRes;
    private javax.swing.JTextField txtUser;
    private javax.swing.JLabel verdeLabel;
    // End of variables declaration//GEN-END:variables
}
