/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp4punto3;

/**
 *
 * @author Fran
 */
public class Ventana extends javax.swing.JFrame {
    private Reloj cronometro, reloj;
    private TareaSemaforo semaforo;

    /**
     * Creates new form Ventana
     * Inicializa el reloj y ejecuta el hilo
     * Inicializa el cronometro, pero no ejecuta el hilo
     * Setea los iconos del semaforo (amarillo y verde null, el rojo con su imagen) y ejecuta el hilo
     */
    public Ventana() {
        initComponents();
        reloj = new Reloj(HLabel, MLabel, SLabel);
        reloj.start();
        cronometro = new Reloj(cronHLabel, cronMLabel, cronSLabel);
        amarilloLabel.setIcon(null);
        amarilloLabel.setText(null);
        verdeLabel.setIcon(null);
        verdeLabel.setText(null);
        semaforo = new TareaSemaforo(rojoLabel, amarilloLabel, verdeLabel, SLabel, 1000);
        semaforo.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        HLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        MLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        SLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        rojoLabel = new javax.swing.JLabel();
        amarilloLabel = new javax.swing.JLabel();
        verdeLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        inicioButton = new javax.swing.JButton();
        pararButton = new javax.swing.JButton();
        cronHLabel = new javax.swing.JLabel();
        cronMLabel = new javax.swing.JLabel();
        cronSLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        HLabel.setText("00");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel5.setText(":");

        MLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        MLabel.setText("00");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel6.setText(":");

        SLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        SLabel.setText("00");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Reloj Temporal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(HLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel1)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HLabel)
                    .addComponent(MLabel)
                    .addComponent(SLabel)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reloj", jPanel2);

        jPanel3.setBackground(java.awt.Color.white);

        rojoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tp4punto3/rojo.png"))); // NOI18N
        rojoLabel.setText("jLabel7");
        rojoLabel.setMaximumSize(new java.awt.Dimension(50, 50));
        rojoLabel.setMinimumSize(new java.awt.Dimension(50, 50));
        rojoLabel.setPreferredSize(new java.awt.Dimension(50, 50));

        amarilloLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tp4punto3/amarillo.png"))); // NOI18N
        amarilloLabel.setText("jLabel2");
        amarilloLabel.setMaximumSize(new java.awt.Dimension(50, 50));
        amarilloLabel.setMinimumSize(new java.awt.Dimension(50, 50));
        amarilloLabel.setPreferredSize(new java.awt.Dimension(50, 50));

        verdeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tp4punto3/verde.png"))); // NOI18N
        verdeLabel.setText("jLabel9");
        verdeLabel.setMaximumSize(new java.awt.Dimension(50, 50));
        verdeLabel.setMinimumSize(new java.awt.Dimension(50, 50));
        verdeLabel.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(verdeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rojoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amarilloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(rojoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(amarilloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(verdeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Semaforo", jPanel3);

        inicioButton.setText("Iniciar");
        inicioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioButtonActionPerformed(evt);
            }
        });

        pararButton.setText("Parar");
        pararButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pararButtonActionPerformed(evt);
            }
        });

        cronHLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        cronHLabel.setText("00");

        cronMLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        cronMLabel.setText("00");

        cronSLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        cronSLabel.setText("00");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setText(":");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setText(":");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cronHLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cronMLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cronSLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inicioButton)
                            .addComponent(pararButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(inicioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cronHLabel)
                    .addComponent(cronMLabel)
                    .addComponent(cronSLabel)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pararButton)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cronometro", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Setea el cronometro a 00:00:00, lo ejecuta y desactiva el boton de inicio
     * @param evt 
     */
    private void inicioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioButtonActionPerformed
        cronHLabel.setText("00");
        cronMLabel.setText("00");
        cronSLabel.setText("00");
        cronometro = new Reloj(cronHLabel, cronMLabel, cronSLabel);
        cronometro.start();
        inicioButton.setEnabled(false);
    }//GEN-LAST:event_inicioButtonActionPerformed
    
    /**
     * Detiene el hilo del cronometro y vuelve a activar el boton de inicio
     * @param evt 
     */
    private void pararButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pararButtonActionPerformed
        cronometro.stop();
        inicioButton.setEnabled(true);
    }//GEN-LAST:event_pararButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HLabel;
    private javax.swing.JLabel MLabel;
    private javax.swing.JLabel SLabel;
    private javax.swing.JLabel amarilloLabel;
    private javax.swing.JLabel cronHLabel;
    private javax.swing.JLabel cronMLabel;
    private javax.swing.JLabel cronSLabel;
    private javax.swing.JButton inicioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton pararButton;
    private javax.swing.JLabel rojoLabel;
    private javax.swing.JLabel verdeLabel;
    // End of variables declaration//GEN-END:variables
}
